### ISSUE TITLE
How do I use it

### ISSUE THREAD

**Issue by donggua2096** [donatmarko/ivao-tracker#12]
How do I use it

**Comment by donatmarko** [comment]
Install the JS and PHP dependencies with npm and composer, create a config according to the sample file with the connection details of the tracker backend SQL db, basically that's it 👍

**Comment by donatmarko** [comment]
Backend: https://github.com/donatmarko/ivao-tracker-backend

**Comment by donggua2096** [comment]
Can you give me a detailed tutorial? I feel my IQ is not enough



---Original---

**Comment by donggua2096** [comment]
And where are the demo files

**Comment by donggua2096** [comment]
main.py What is it for

**Comment by donggua2096** [comment]
![Uploading (W`3ID4$@{PS2VRTTB28%JJ.png…]()

**Comment by donggua2096** [comment]
[root@izc9bfkgjlj5w6z ~]# cd /www/wwwroot/47.94.145.202
[root@izc9bfkgjlj5w6z 47.94.145.202]# npm install
npm ERR! code ERR_TLS_CERT_ALTNAME_INVALID
npm ERR! errno ERR_TLS_CERT_ALTNAME_INVALID
npm ERR! request to https://registry.cnpmjs.org/jquery failed, reason: Hostname/IP does not match certificate's altnames: Host: registry.cnpmjs.org. is not in the cert's altnames: DNS:r.cnpmjs.org

**Comment by donggua2096** [comment]
[root@izc9bfkgjlj5w6z 47.94.145.202]# composer install
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/usr/bin/composer self-update" to get the latest version.
Composer could not find a composer.json file in /www/wwwroot/47.94.145.202
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
[root@izc9bfkgjlj5w6z 47.94.145.202]#

**Comment by donatmarko** [comment]
Hello,
Unfortunately I don't have capacity to create detailed tutorial for such projects of me, I have no intentions to develop it further, so I granted it to the public domain.
There are no demo files, they are not needed either as this repository contains complete and more or less usable map, and the data should come from the live IVAO Whazzup through the other project (backend) I linked above.
The main.py of the backend repository is the data collector script itself that should be run by cronjob in every 3 minutes or so.

**Comment by donggua2096** [comment]
---Original---

**Comment by donggua2096** [comment]
When I run the script, I prompt
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\新建文件夹\main.py", line 4, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
>>> 
How to solve this problem

**Comment by donatmarko** [comment]
It's a self-explanatory error. You must install the mysql module in order to run the code.
Indeed the requirements.txt is missing from that repo, but the necessary modules can be found in the first lines of main.py.

**Comment by donggua2096** [comment]
I did, but now the problem is that when I run it correctly, the script program prompts me to report an error when the MySQL time zone is different



---Original---

**Comment by donggua2096** [comment]
mysql.connector.errors.DatabaseError: 1298 (HY000): Unknown or incorrect time zone: 'Etc/UTC

**Comment by donatmarko** [comment]
Please look it up on Google. It is a common error not related to my application but MySQL itself.
https://dba.stackexchange.com/questions/120945/how-do-i-resolve-this-error-error-1298-hy000-unknown-or-incorrect-time-zone

**Comment by donggua2096** [comment]
I'm very sorry to trouble you. Thank you
